name: CI/CD for Node.js IOT Server

on:
  push:
    branches:
      - init_project

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust to your Node.js version
      - name: Install dependencies
        run: npm install
      # Fetch the secret variable and set it as an environment variable
      - name: Set JWT Secret Key
        run: echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
      - name: Fix permissions of node_modules/.bin
        run: sudo chmod +x node_modules/.bin/*
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test

  deploy:
    needs: test # Only runs if tests pass
    runs-on: self-hosted # Runs on your cm4stack
    steps:
      # - name: Change to webserver directory
      #   run: cd /home/pi/CICD/webserver-cicd-test # Adjust to your project directory
      - name: Switch to init_project branch
        run: git checkout init_project
      - name: Pull latest code
        run: git pull origin init_project 
      - name: Install dependencies
        run: npm install
      - name: Reload iot server
        run: sudo systemctl reload iotserver
      - name: Check git status
        run: git status
      - name: Check git branch
        run: git branch